# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2021 Intel Corporation
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: sriov-fec.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: SriovFecClusterConfig is the Schema for the sriovfecclusterconfigs
        API
      displayName: SriovFecClusterConfig
      kind: SriovFecClusterConfig
      name: sriovfecclusterconfigs.sriovfec.intel.com
      resources:
      - kind: SriovFecNodeConfig
        name: node
        version: v1
      specDescriptors:
      - description: List of node configurations
        displayName: Nodes
        path: nodes
      - description: List of physical functions (cards) configs
        displayName: Physical Functions
        path: nodes[0].physicalFunctions
      statusDescriptors:
      - description: Indicates the synchronization status of the CR
        displayName: Sync Status
        path: syncStatus
      version: v1
    - description: SriovFecNodeConfig is the Schema for the sriovfecnodeconfigs API
      displayName: SriovFecNodeConfig
      kind: SriovFecNodeConfig
      name: sriovfecnodeconfigs.sriovfec.intel.com
      resources:
      - kind: SriovFecNodeConfig
        name: node
        version: v1
      specDescriptors:
      - description: List of PhysicalFunctions configs
        displayName: Physical Functions
        path: physicalFunctions
      statusDescriptors:
      - description: Provides information about FPGA inventory on the node
        displayName: Inventory
        path: inventory
      version: v1
    - description: SriovFecClusterConfig is the Schema for the sriovfecclusterconfigs
        API
      displayName: SriovFecClusterConfig
      kind: SriovFecClusterConfig
      name: sriovfecclusterconfigs.sriovfec.intel.com
      resources:
      - kind: SriovFecNodeConfig
        name: node
        version: v2
      specDescriptors:
      - description: Selector describes target accelerator for this spec
        displayName: Accelerator Selector
        path: acceleratorSelector
      - description: Skips drain process when true; default false. Should be true
          if operator is running on SNO
        displayName: Drain Skip
        path: drainSkip
      - description: Selector describes target node for this spec
        displayName: Node Selector
        path: nodeSelector
      - description: List of node configurations. This element is deprecated and should
          not be use because it will be removed in next release of sriov-fec operator.
        displayName: Nodes
        path: nodes
      - description: List of physical functions (cards) configs
        displayName: Physical Functions
        path: nodes[0].physicalFunctions
      - description: Physical function (card) config
        displayName: Physical Function
        path: physicalFunction
      - description: Higher priority policies can override lower ones.
        displayName: Priority
        path: priority
      statusDescriptors:
      - description: Indicates the synchronization status of the CR
        displayName: Sync Status
        path: syncStatus
      version: v2
    - description: SriovFecNodeConfig is the Schema for the sriovfecnodeconfigs API
      displayName: SriovFecNodeConfig
      kind: SriovFecNodeConfig
      name: sriovfecnodeconfigs.sriovfec.intel.com
      resources:
      - kind: SriovFecNodeConfig
        name: node
        version: v1
      specDescriptors:
      - description: Skips drain process when true; default false. Should be true
          if operator is running on SNO
        displayName: Drain Skip
        path: drainSkip
      - description: List of PhysicalFunctions configs
        displayName: Physical Functions
        path: physicalFunctions
      statusDescriptors:
      - description: Provides information about FPGA inventory on the node
        displayName: Inventory
        path: inventory
      version: v2
  description: "The Intel® FPGA Programmable Acceleration Card N3000 (Intel® FPGA
    PAC N3000) is a highly customizable FPGA SmartNIC which enables high-throughput,
    low latency and high-bandwith applications.  It allows the optimization of data
    plane performance to reduce total cost of ownership while maintaining a high degree
    of flexibility.  The Intel FPGA PAC N3000 plays a key role in accelerating 5G
    and network functions virtualization (NFV) adoption for ecosystem partners such
    as telecommunications equipment manufacturers (TEMs) virtual network functions
    (VNF) vendors, system integrators and telcos, to bring scalable and high-performance
    solutions to market. The Intel FPGA PAC N3000 includes a variant that is design
    to be Network Equipment Building System (NEBS)-friendly, and features a Root-of-Trust
    device that helps protect systems from FPGA host security exploits. This document
    explains how the FPGA resource can be used on the Open Network Edge Services Software
    (OpenNESS) platform for accelerating network functions and edge application workloads.
    We use the Intel® FPGA PAC N3000 as a reference FPGA PAC and use LTE/5G Forward
    Error Correction (FEC) as an example workload that accelerates the 5G or 4G L1
    base station network function. The same concept and mechanism is applicable for
    application acceleration workloads like AI and ML on FPGA for Inference applications.
    The Intel® FPGA PAC N3000 is a full-duplex, 100 Gbps in-system, re-programmable
    acceleration card for multi-workload networking application acceleration. It has
    an optimal memory mixture designed for network functions, with an integrated network
    interface card (NIC) in a small form factor that enables high throughput, low
    latency, and low power per bit for a custom networking pipeline. The ACC100 supports
    the O-RAN adopted DPDK BBDev API - an API which Intel contributed to the opensource
    community to enable choice and TTM for FEC acceleration solutions. The FlexRAN
    software reference architecture supports the ACC100 which enables users to quickly
    evaluate and build platforms for the wide range of vRAN networks. Reduces platform
    power, E2E latency and Intel® CPU core count requirements as well as increases
    cell capacity than existing programmable accelerator. Accelerates both 4G and
    5G data concurrently.\tLowers development cost using commercial off the shelf
    (COTS) servers. Accommodates space-constrained implementations via a low-profile
    PCIe card form factor. Enables a variety of flexible FlexRAN deployments from
    small cell to macro to Massive MIMO networks. Supports extended temperature for
    the most challenging of RAN deployment scenario’s."
  displayName: OpenNESS SR-IOV Operator for Wireless FEC Accelerators
  icon:
  - base64data: PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDI0LjMuMCwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPgo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6eGxpbms9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkveGxpbmsiIHg9IjBweCIgeT0iMHB4IgoJIHZpZXdCb3g9IjAgMCA3MiAzMCIgc3R5bGU9ImVuYWJsZS1iYWNrZ3JvdW5kOm5ldyAwIDAgNzIgMzA7IiB4bWw6c3BhY2U9InByZXNlcnZlIj4KPHN0eWxlIHR5cGU9InRleHQvY3NzIj4KCS5zdDB7ZmlsbDojMDA2OEI1O30KPC9zdHlsZT4KPGc+Cgk8cmVjdCB4PSIxLjgiIHk9IjIuMSIgY2xhc3M9InN0MCIgd2lkdGg9IjQuOTYiIGhlaWdodD0iNC45NiIvPgoJPHBhdGggY2xhc3M9InN0MCIgZD0iTTYuNjMsMjcuOVYxMC4wNmgtNC43VjI3LjlINi42M3ogTTM3Ljc4LDI4LjA4di00LjM3Yy0wLjY5LDAtMS4yNi0wLjA0LTEuNy0wLjExCgkJYy0wLjQ4LTAuMDgtMC44Ni0wLjI0LTEuMS0wLjQ5Yy0wLjI1LTAuMjUtMC40MS0wLjYxLTAuNDktMS4wN2MtMC4wNy0wLjQ0LTAuMTEtMS4wMi0wLjExLTEuNzJ2LTYuMjRoMy40di00LjAyaC0zLjRWMy4xMWgtNC43CgkJdjE3LjI0YzAsMS40NSwwLjEzLDIuNjksMC4zOCwzLjY4YzAuMjUsMC45NywwLjY3LDEuNzcsMS4yNSwyLjM3YzAuNTgsMC42LDEuMzYsMS4wMywyLjI5LDEuMjljMC45NSwwLjI2LDIuMTUsMC4zOSwzLjU4LDAuMzkKCQlIMzcuNzh6IE02NC43MSwyNy45VjEuNzRoLTQuN1YyNy45SDY0LjcxeiBNMjUuMTUsMTEuODJDMjMuODQsMTAuNDEsMjIsOS43LDE5LjY4LDkuN2MtMS4xMiwwLTIuMTYsMC4yMy0zLjA4LDAuNjkKCQljLTAuOTIsMC40Ni0xLjcxLDEuMS0yLjMzLDEuOWwtMC4yNiwwLjMzbDAtMC4zdi0yLjI2SDkuMzdWMjcuOWg0LjY3di05LjVsMCwwLjY2YzAtMC4xMSwwLTAuMjIsMC0wLjMyCgkJYzAuMDUtMS42NywwLjQ2LTIuOTEsMS4yNC0zLjdjMC44My0wLjg0LDEuODMtMS4yNywyLjk4LTEuMjdjMS4zNiwwLDIuMzksMC40MiwzLjA4LDEuMjNjMC42NywwLjgsMS4wMSwxLjk1LDEuMDIsMy40MmwwLDB2MC4wNAoJCWMwLDAsMCwwLjAxLDAsMC4wMWgwbDAsOS40M2g0Ljc0VjE3Ljc3QzI3LjExLDE1LjIzLDI2LjQ1LDEzLjIzLDI1LjE1LDExLjgyeiBNNTcuNTYsMTguOTRjMC0xLjI4LTAuMjMtMi40OS0wLjY4LTMuNjEKCQljLTAuNDUtMS4xMS0xLjA5LTIuMS0xLjg5LTIuOTVjLTAuOC0wLjg0LTEuNzgtMS41MS0yLjkxLTEuOThDNTAuOTYsOS45NCw0OS43LDkuNyw0OC4zNSw5LjdjLTEuMjgsMC0yLjUsMC4yNS0zLjYyLDAuNzMKCQljLTEuMTMsMC40OS0yLjEyLDEuMTUtMi45NSwxLjk4Yy0wLjgzLDAuODMtMS41LDEuODItMS45OCwyLjk1Yy0wLjQ5LDEuMTItMC43MywyLjM0LTAuNzMsMy42MmMwLDEuMjgsMC4yMywyLjUsMC43LDMuNjIKCQljMC40NiwxLjEzLDEuMTEsMi4xMiwxLjkzLDIuOTRjMC44MiwwLjgzLDEuODIsMS41LDIuOTgsMS45OGMxLjE2LDAuNDksMi40NSwwLjczLDMuODIsMC43M2MzLjk4LDAsNi40Ni0xLjgxLDcuOTQtMy41bC0zLjM4LTIuNTgKCQljLTAuNzEsMC44NS0yLjQsMS45OS00LjUyLDEuOTljLTEuMzMsMC0yLjQyLTAuMzEtMy4yNC0wLjkxYy0wLjgzLTAuNjEtMS40LTEuNDQtMS43LTIuNDhsLTAuMDUtMC4xN2gxNC4wMVYxOC45NHogTTQzLjU5LDE3LjMxCgkJYzAtMS4zMSwxLjUtMy41OSw0LjczLTMuNTljMy4yMywwLDQuNzMsMi4yOCw0LjczLDMuNThMNDMuNTksMTcuMzF6Ii8+Cgk8cGF0aCBjbGFzcz0ic3QwIiBkPSJNNzAuMDYsMjUuNjVjLTAuMDktMC4yMS0wLjIyLTAuMzktMC4zNy0wLjU1Yy0wLjE2LTAuMTYtMC4zNC0wLjI4LTAuNTUtMC4zN2MtMC4yMS0wLjA5LTAuNDQtMC4xNC0wLjY4LTAuMTQKCQljLTAuMjQsMC0wLjQ3LDAuMDUtMC42OCwwLjE0Yy0wLjIxLDAuMDktMC4zOSwwLjIyLTAuNTUsMC4zN2MtMC4xNiwwLjE2LTAuMjgsMC4zNC0wLjM3LDAuNTVjLTAuMDksMC4yMS0wLjE0LDAuNDQtMC4xNCwwLjY4CgkJYzAsMC4yNCwwLjA1LDAuNDcsMC4xNCwwLjY4YzAuMDksMC4yMSwwLjIyLDAuMzksMC4zNywwLjU1YzAuMTYsMC4xNiwwLjM0LDAuMjgsMC41NSwwLjM3YzAuMjEsMC4wOSwwLjQ0LDAuMTQsMC42OCwwLjE0CgkJYzAuMjQsMCwwLjQ3LTAuMDUsMC42OC0wLjE0YzAuMjEtMC4wOSwwLjM5LTAuMjIsMC41NS0wLjM3YzAuMTYtMC4xNiwwLjI4LTAuMzQsMC4zNy0wLjU1YzAuMDktMC4yMSwwLjE0LTAuNDQsMC4xNC0wLjY4CgkJQzcwLjIsMjYuMDksNzAuMTUsMjUuODYsNzAuMDYsMjUuNjV6IE02OS43OCwyNi44OGMtMC4wNywwLjE3LTAuMTgsMC4zMy0wLjMxLDAuNDZjLTAuMTMsMC4xMy0wLjI4LDAuMjMtMC40NiwwLjMxCgkJYy0wLjE3LDAuMDctMC4zNiwwLjExLTAuNTYsMC4xMWMtMC4yLDAtMC4zOC0wLjA0LTAuNTYtMC4xMWMtMC4xNy0wLjA3LTAuMzMtMC4xOC0wLjQ2LTAuMzFjLTAuMTMtMC4xMy0wLjIzLTAuMjgtMC4zMS0wLjQ2CgkJYy0wLjA3LTAuMTctMC4xMS0wLjM2LTAuMTEtMC41NmMwLTAuMiwwLjA0LTAuMzgsMC4xMS0wLjU2YzAuMDctMC4xNywwLjE4LTAuMzMsMC4zMS0wLjQ2YzAuMTMtMC4xMywwLjI4LTAuMjMsMC40Ni0wLjMxCgkJYzAuMTctMC4wNywwLjM2LTAuMTEsMC41Ni0wLjExYzAuMiwwLDAuMzgsMC4wNCwwLjU2LDAuMTFjMC4xNywwLjA3LDAuMzMsMC4xOCwwLjQ2LDAuMzFjMC4xMywwLjEzLDAuMjMsMC4yOCwwLjMxLDAuNDYKCQljMC4wNywwLjE3LDAuMTEsMC4zNiwwLjExLDAuNTZDNjkuODksMjYuNTIsNjkuODUsMjYuNzEsNjkuNzgsMjYuODh6IE02OC43OSwyNi40N2MwLjE0LTAuMDIsMC4yNS0wLjA3LDAuMzQtMC4xNQoJCWMwLjA5LTAuMDksMC4xMy0wLjIyLDAuMTMtMC4zOWMwLTAuMTktMC4wNi0wLjM0LTAuMTctMC40NGMtMC4xMS0wLjEtMC4yOS0wLjE1LTAuNTMtMC4xNWgtMC43N3YxLjk5aDAuMzZ2LTAuODFoMC4yN2wwLjUsMC44MQoJCWgwLjM4TDY4Ljc5LDI2LjQ3eiBNNjguNTksMjYuMThjLTAuMDYsMC0wLjExLDAuMDEtMC4xNywwLjAxaC0wLjI3di0wLjU2aDAuMjdjMC4wNiwwLDAuMTEsMCwwLjE3LDBjMC4wNiwwLDAuMTEsMC4wMSwwLjE1LDAuMDMKCQljMC4wNSwwLjAyLDAuMDgsMC4wNSwwLjExLDAuMDhjMC4wMywwLjA0LDAuMDQsMC4wOSwwLjA0LDAuMTVzLTAuMDEsMC4xMi0wLjA0LDAuMTVjLTAuMDMsMC4wNC0wLjA2LDAuMDctMC4xMSwwLjA4CgkJQzY4LjcsMjYuMTYsNjguNjUsMjYuMTcsNjguNTksMjYuMTh6Ii8+CjwvZz4KPC9zdmc+Cg==
    mediatype: image/svg+xml
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - N3000
  - N3000-2
  - N3000-n
  - ACC100
  - vRAN
  - ORAN
  - fpga accelerator
  links:
  - name: Sriov Fec
    url: https://sriov-fec.domain
  maturity: alpha
  provider:
    name: Intel Corporation
    url: https://www.intel.com/content/www/us/en/programmable/products/boards_and_kits/dev-kits/altera/intel-fpga-pac-n3000/overview.html
  version: 0.0.0
