# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020-2021 Intel Corporation
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: n3000.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: N3000Cluster is the Schema for the n3000clusters API
      displayName: N3000Cluster
      kind: N3000Cluster
      name: n3000clusters.fpga.intel.com
      resources:
      - kind: N3000Node
        name: n3000-worker
        version: v1
      specDescriptors:
      - description: List of the nodes with their devices to be updated
        displayName: Nodes
        path: nodes
      statusDescriptors:
      - description: Indicates the synchronization status of the CR
        displayName: Sync Status
        path: syncStatus
      version: v1
    - description: N3000Node is the Schema for the n3000nodes API
      displayName: N3000 Node
      kind: N3000Node
      name: n3000nodes.fpga.intel.com
      specDescriptors:
      - description: Fortville devices to be updated
        displayName: Fortville
        path: fortville
      - description: FPGA devices to be updated
        displayName: FPGA
        path: fpga
      statusDescriptors:
      - description: Provides information about N3000 Fortville invetory on the node
        displayName: Fortville
        path: fortville
      - description: Provides information about FPGA inventory on the node
        displayName: FPGA
        path: fpga
      version: v1
  description: The Intel® FPGA Programmable Acceleration Card N3000 (Intel® FPGA PAC N3000) is a highly customizable FPGA SmartNIC which enables high-throughput, low latency and high-bandwith applications.  It allows the optimization of data plane performance to reduce total cost of ownership while maintaining a high degree of flexibility.  The Intel FPGA PAC N3000 plays a key role in accelerating 5G and network functions virtualization (NFV) adoption for ecosystem partners such as telecommunications equipment manufacturers (TEMs) virtual network functions (VNF) vendors, system integrators and telcos, to bring scalable and high-performance solutions to market. The Intel FPGA PAC N3000 includes a variant that is design to be Network Equipment Building System (NEBS)-friendly, and features a Root-of-Trust device that helps protect systems from FPGA host security exploits. This document explains how the FPGA resource can be used on the Open Network Edge Services Software (OpenNESS) platform for accelerating network functions and edge application workloads. We use the Intel® FPGA PAC N3000 as a reference FPGA PAC and use LTE/5G Forward Error Correction (FEC) as an example workload that accelerates the 5G or 4G L1 base station network function. The same concept and mechanism is applicable for application acceleration workloads like AI and ML on FPGA for Inference applications. The Intel® FPGA PAC N3000 is a full-duplex, 100 Gbps in-system, re-programmable acceleration card for multi-workload networking application acceleration. It has an optimal memory mixture designed for network functions, with an integrated network interface card (NIC) in a small form factor that enables high throughput, low latency, and low power per bit for a custom networking pipeline.
  displayName: OpenNESS Operator for Intel® FPGA PAC N3000
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - N3000
  - N3000-2
  - vRAN
  - ORAN
  - fpga accelerator
  links:
  - name: N3000
    url: https://n3000.domain
  maturity: alpha
  provider:
    name: Intel Corporation
    url: https://www.intel.com/content/www/us/en/programmable/products/boards_and_kits/dev-kits/altera/intel-fpga-pac-n3000/overview.html
  version: 0.0.0
