# permissions for end users to view sriovfecclusterconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sriovfecclusterconfig-viewer-role
rules:
- apiGroups:
  - sriovfec.intel.com
  resources:
  - sriovfecclusterconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sriovfec.intel.com
  resources:
  - sriovfecclusterconfigs/status
  verbs:
  - get
