# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: n3000clusters.fpga.intel.com
spec:
  group: fpga.intel.com
  names:
    kind: N3000Cluster
    listKind: N3000ClusterList
    plural: n3000clusters
    singular: n3000cluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: N3000Cluster is the Schema for the n3000clusters API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: N3000ClusterSpec defines the desired state of N3000Cluster
          properties:
            drainSkip:
              type: boolean
            dryrun:
              type: boolean
            nodes:
              items:
                properties:
                  fortville:
                    properties:
                      MACs:
                        items:
                          properties:
                            MAC:
                              pattern: ^[a-f0-9]{2}:[a-f0-9]{2}:[a-f0-9]{2}:[a-f0-9]{2}:[a-f0-9]{2}:[a-f0-9]{2}$
                              type: string
                          type: object
                        type: array
                      checksum:
                        pattern: ^[a-fA-F0-9]{32}$
                        type: string
                      firmwareURL:
                        pattern: '[a-zA-Z0-9\.\-\/]+'
                        type: string
                    type: object
                  fpga:
                    items:
                      properties:
                        PCIAddr:
                          pattern: ^[a-fA-F0-9]{4}:[a-fA-F0-9]{2}:[a-fA-F0-9]{2}\.[0-9]$
                          type: string
                        checksum:
                          pattern: ^[a-fA-F0-9]{32}$
                          type: string
                        userImageURL:
                          pattern: '[a-zA-Z0-9\.\-\/]+'
                          type: string
                      type: object
                    type: array
                  nodeName:
                    pattern: '[a-z0-9\.\-]+'
                    type: string
                required:
                - nodeName
                type: object
              type: array
          required:
          - nodes
          type: object
        status:
          description: N3000ClusterStatus defines the observed state of N3000Cluster
          properties:
            lastSyncError:
              type: string
            syncStatus:
              type: string
          type: object
      type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
